// SteamLite 9.1.0 - more languages. The main screens, menus and buttons are translated (anything not listed stays in English).
// Pick the language in Tools & extras > More settings (or Extras settings).
(function () {
    'use strict';
    if (!window.SLF || !SLF.DICTS) return;
    const L = {};
    L.es = {
        'Home': 'Inicio', 'Library': 'Biblioteca', 'Favorites': 'Favoritos', 'Settings': 'Ajustes', 'Dashboard': 'Panel', 'Collections': 'Colecciones', 'COLLECTIONS': 'COLECCIONES', 'Profile': 'Perfil', 'Friend Profile': 'Perfil del amigo',
        'Online': 'En línea', 'Offline': 'Desconectado', 'Away': 'Ausente', 'Installed': 'Instalado', 'Not Installed': 'No instalado', 'Play': 'Jugar', 'Install': 'Instalar', 'Uninstall': 'Desinstalar', 'Cancel': 'Cancelar', 'Save': 'Guardar', 'Close': 'Cerrar',
        'Refresh': 'Actualizar', 'Apply': 'Aplicar', 'Locked': 'Bloqueado', 'Search library...': 'Buscar en la biblioteca...', 'Play Next': 'Jugar siguiente', 'Friends List': 'Lista de amigos', 'Search friends...': 'Buscar amigos...', 'Show hidden': 'Mostrar ocultos',
        'Activity': 'Actividad', 'Right-click a friend for more': 'Clic derecho en un amigo para más', 'Application Settings': 'Ajustes de la aplicación', 'Modify your preferences below': 'Cambia tus preferencias abajo', 'Advanced Settings': 'Ajustes avanzados',
        'Save Configuration': 'Guardar configuración', 'Check for Updates': 'Buscar actualizaciones', 'Filters': 'Filtros', 'Sort By': 'Ordenar por', 'Hide Shared': 'Ocultar compartidos', 'Show Hidden': 'Mostrar ocultos', 'Compact List': 'Lista compacta',
        'My status': 'Mi estado', 'Playing': 'Jugando', 'Backlog': 'Pendiente', 'Completed': 'Completado', 'Dropped': 'Abandonado', 'Inventory': 'Inventario', 'Achievements': 'Logros', 'SteamLite Achievements': 'Logros de SteamLite', 'Wishlist': 'Lista de deseados',
        'Daily challenges': 'Desafíos diarios', 'Weekly challenges': 'Desafíos semanales', 'Items': 'Objetos', 'Level rewards': 'Recompensas de nivel', 'Rewards earned': 'Recompensas obtenidas', 'Streak Restores': 'Restauraciones de racha', 'Play Streak': 'Racha de juego',
        'Year in Review': 'Resumen del año', 'Friend Activity': 'Actividad de amigos', 'Notification history': 'Historial de notificaciones', 'Tools & extras': 'Herramientas y extras', 'Extras settings': 'Ajustes de extras', 'Diagnostics': 'Diagnóstico',
        'Automatic backups': 'Copias automáticas', 'What should I play?': '¿A qué juego?', 'Up Next': 'A continuación', 'Play calendar': 'Calendario de juego', 'Library stats': 'Estadísticas de la biblioteca', 'Co-op finder': 'Buscador cooperativo',
        'Game journal': 'Diario de juegos', 'Weekly bingo': 'Bingo semanal', 'Season': 'Temporada', 'Free games & sales': 'Juegos gratis y ofertas', 'Library health': 'Salud de la biblioteca', 'Shutdown timer': 'Temporizador de apagado',
        'Closest to 100%': 'Más cerca del 100%', 'Home Title': 'Inicio', 'Select multiple games': 'Seleccionar varios juegos', 'Launch Options': 'Opciones de inicio', 'Game Notes': 'Notas del juego', 'Session History': 'Historial de sesiones',
        'Screenshots': 'Capturas', 'Details': 'Detalles', 'News': 'Noticias', 'Hide Game': 'Ocultar juego', 'Unhide Game': 'Mostrar juego', 'Add to Favorites': 'Añadir a favoritos', 'Remove from Favorites': 'Quitar de favoritos', 'Change Cover': 'Cambiar portada',
        'Edit Profile': 'Editar perfil', 'Badges': 'Insignias', 'Showcase': 'Vitrina', 'Owned Games': 'Juegos en propiedad', 'Level': 'Nivel', 'Games': 'Juegos', 'Playtime': 'Tiempo de juego', 'Loading...': 'Cargando...', 'No friends to show.': 'No hay amigos que mostrar.',
        'Update Now': 'Actualizar ahora', 'Later': 'Más tarde', "What's new": 'Novedades', 'Skip this version': 'Omitir esta versión', 'Back': 'Atrás', 'Next': 'Siguiente', 'Done': 'Hecho', 'Yes': 'Sí', 'No': 'No', 'OK': 'Aceptar', 'Delete': 'Eliminar', 'Add': 'Añadir', 'Remove': 'Quitar',
        'Appearance (card style, font, UI scale)': 'Apariencia (estilo de tarjetas, fuente, escala)', 'Keyboard Shortcuts': 'Atajos de teclado', 'Global Hotkeys': 'Atajos globales', 'Quit SteamLite': 'Salir de SteamLite', 'Go to Home': 'Ir al inicio', 'Go to Library': 'Ir a la biblioteca',
        'Go to Favorites': 'Ir a favoritos', 'Open Settings': 'Abrir ajustes', 'Toggle Friends Panel': 'Mostrar/ocultar amigos', 'Play Random Game': 'Jugar al azar', 'Free Up Space (disk cleanup)': 'Liberar espacio (limpieza de disco)', 'Import Games from Start Menu': 'Importar juegos del menú Inicio',
        'Drops': 'Regalos', 'Shop': 'Tienda', 'Trophy room': 'Sala de trofeos', 'Events': 'Eventos', 'Claim': 'Reclamar', 'Quick access': 'Acceso rápido', 'Notifications': 'Notificaciones', 'Account': 'Cuenta', 'Appearance': 'Apariencia', 'Sound & notifications': 'Sonido y notificaciones',
        'Behaviour': 'Comportamiento', 'Performance': 'Rendimiento', 'Updates': 'Actualizaciones', 'Backup & data': 'Copia y datos', 'Lucky wheel': 'Ruleta de la suerte', 'Spin': 'Girar'
    };
    L.fr = {
        'Home': 'Accueil', 'Library': 'Bibliothèque', 'Favorites': 'Favoris', 'Settings': 'Paramètres', 'Dashboard': 'Tableau de bord', 'Collections': 'Collections', 'COLLECTIONS': 'COLLECTIONS', 'Profile': 'Profil', 'Friend Profile': "Profil de l'ami",
        'Online': 'En ligne', 'Offline': 'Hors ligne', 'Away': 'Absent', 'Installed': 'Installé', 'Not Installed': 'Non installé', 'Play': 'Jouer', 'Install': 'Installer', 'Uninstall': 'Désinstaller', 'Cancel': 'Annuler', 'Save': 'Enregistrer', 'Close': 'Fermer',
        'Refresh': 'Actualiser', 'Apply': 'Appliquer', 'Locked': 'Verrouillé', 'Search library...': 'Rechercher dans la bibliothèque...', 'Play Next': 'Jouer ensuite', 'Friends List': 'Liste d\'amis', 'Search friends...': 'Rechercher des amis...', 'Show hidden': 'Afficher les masqués',
        'Activity': 'Activité', 'Right-click a friend for more': 'Clic droit sur un ami pour plus', 'Application Settings': "Paramètres de l'application", 'Modify your preferences below': 'Modifiez vos préférences ci-dessous', 'Advanced Settings': 'Paramètres avancés',
        'Save Configuration': 'Enregistrer la configuration', 'Check for Updates': 'Rechercher des mises à jour', 'Filters': 'Filtres', 'Sort By': 'Trier par', 'Hide Shared': 'Masquer les partagés', 'Show Hidden': 'Afficher les masqués', 'Compact List': 'Liste compacte',
        'My status': 'Mon statut', 'Playing': 'En cours', 'Backlog': 'À faire', 'Completed': 'Terminé', 'Dropped': 'Abandonné', 'Inventory': 'Inventaire', 'Achievements': 'Succès', 'SteamLite Achievements': 'Succès SteamLite', 'Wishlist': 'Liste de souhaits',
        'Daily challenges': 'Défis quotidiens', 'Weekly challenges': 'Défis hebdomadaires', 'Items': 'Objets', 'Level rewards': 'Récompenses de niveau', 'Rewards earned': 'Récompenses obtenues', 'Streak Restores': 'Restaurations de série', 'Play Streak': 'Série de jeu',
        'Year in Review': "Bilan de l'année", 'Friend Activity': 'Activité des amis', 'Notification history': 'Historique des notifications', 'Tools & extras': 'Outils et extras', 'Extras settings': 'Paramètres des extras', 'Diagnostics': 'Diagnostic',
        'Automatic backups': 'Sauvegardes automatiques', 'What should I play?': 'À quoi jouer ?', 'Up Next': 'À suivre', 'Play calendar': 'Calendrier de jeu', 'Library stats': 'Statistiques de la bibliothèque', 'Co-op finder': 'Recherche de coop',
        'Game journal': 'Journal de jeu', 'Weekly bingo': 'Bingo hebdomadaire', 'Season': 'Saison', 'Free games & sales': 'Jeux gratuits et promos', 'Library health': 'Santé de la bibliothèque', 'Shutdown timer': "Minuterie d'arrêt",
        'Closest to 100%': 'Plus proches de 100 %', 'Home Title': 'Accueil', 'Select multiple games': 'Sélectionner plusieurs jeux', 'Launch Options': 'Options de lancement', 'Game Notes': 'Notes du jeu', 'Session History': 'Historique des sessions',
        'Screenshots': "Captures d'écran", 'Details': 'Détails', 'News': 'Actualités', 'Hide Game': 'Masquer le jeu', 'Unhide Game': 'Afficher le jeu', 'Add to Favorites': 'Ajouter aux favoris', 'Remove from Favorites': 'Retirer des favoris', 'Change Cover': 'Changer la jaquette',
        'Edit Profile': 'Modifier le profil', 'Badges': 'Badges', 'Showcase': 'Vitrine', 'Owned Games': 'Jeux possédés', 'Level': 'Niveau', 'Games': 'Jeux', 'Playtime': 'Temps de jeu', 'Loading...': 'Chargement...', 'No friends to show.': 'Aucun ami à afficher.',
        'Update Now': 'Mettre à jour', 'Later': 'Plus tard', "What's new": 'Nouveautés', 'Skip this version': 'Ignorer cette version', 'Back': 'Retour', 'Next': 'Suivant', 'Done': 'Terminé', 'Yes': 'Oui', 'No': 'Non', 'OK': 'OK', 'Delete': 'Supprimer', 'Add': 'Ajouter', 'Remove': 'Retirer',
        'Appearance (card style, font, UI scale)': 'Apparence (style des cartes, police, échelle)', 'Keyboard Shortcuts': 'Raccourcis clavier', 'Global Hotkeys': 'Raccourcis globaux', 'Quit SteamLite': 'Quitter SteamLite', 'Go to Home': "Aller à l'accueil", 'Go to Library': 'Aller à la bibliothèque',
        'Go to Favorites': 'Aller aux favoris', 'Open Settings': 'Ouvrir les paramètres', 'Toggle Friends Panel': 'Afficher/masquer les amis', 'Play Random Game': 'Jouer au hasard', 'Free Up Space (disk cleanup)': "Libérer de l'espace (nettoyage du disque)", 'Import Games from Start Menu': 'Importer les jeux du menu Démarrer',
        'Drops': 'Cadeaux', 'Shop': 'Boutique', 'Trophy room': 'Salle des trophées', 'Events': 'Événements', 'Claim': 'Récupérer', 'Quick access': 'Accès rapide', 'Notifications': 'Notifications', 'Account': 'Compte', 'Appearance': 'Apparence', 'Sound & notifications': 'Son et notifications',
        'Behaviour': 'Comportement', 'Performance': 'Performances', 'Updates': 'Mises à jour', 'Backup & data': 'Sauvegarde et données', 'Lucky wheel': 'Roue de la chance', 'Spin': 'Tourner'
    };
    L.de = {
        'Home': 'Start', 'Library': 'Bibliothek', 'Favorites': 'Favoriten', 'Settings': 'Einstellungen', 'Dashboard': 'Übersicht', 'Collections': 'Sammlungen', 'COLLECTIONS': 'SAMMLUNGEN', 'Profile': 'Profil', 'Friend Profile': 'Profil des Freundes',
        'Online': 'Online', 'Offline': 'Offline', 'Away': 'Abwesend', 'Installed': 'Installiert', 'Not Installed': 'Nicht installiert', 'Play': 'Spielen', 'Install': 'Installieren', 'Uninstall': 'Deinstallieren', 'Cancel': 'Abbrechen', 'Save': 'Speichern', 'Close': 'Schließen',
        'Refresh': 'Aktualisieren', 'Apply': 'Anwenden', 'Locked': 'Gesperrt', 'Search library...': 'Bibliothek durchsuchen...', 'Play Next': 'Als Nächstes spielen', 'Friends List': 'Freundesliste', 'Search friends...': 'Freunde suchen...', 'Show hidden': 'Versteckte anzeigen',
        'Activity': 'Aktivität', 'Right-click a friend for more': 'Rechtsklick auf einen Freund für mehr', 'Application Settings': 'App-Einstellungen', 'Modify your preferences below': 'Passe deine Einstellungen unten an', 'Advanced Settings': 'Erweiterte Einstellungen',
        'Save Configuration': 'Konfiguration speichern', 'Check for Updates': 'Nach Updates suchen', 'Filters': 'Filter', 'Sort By': 'Sortieren nach', 'Hide Shared': 'Geteilte ausblenden', 'Show Hidden': 'Versteckte anzeigen', 'Compact List': 'Kompakte Liste',
        'My status': 'Mein Status', 'Playing': 'Spiele gerade', 'Backlog': 'Backlog', 'Completed': 'Abgeschlossen', 'Dropped': 'Abgebrochen', 'Inventory': 'Inventar', 'Achievements': 'Erfolge', 'SteamLite Achievements': 'SteamLite-Erfolge', 'Wishlist': 'Wunschliste',
        'Daily challenges': 'Tägliche Herausforderungen', 'Weekly challenges': 'Wöchentliche Herausforderungen', 'Items': 'Gegenstände', 'Level rewards': 'Levelbelohnungen', 'Rewards earned': 'Erhaltene Belohnungen', 'Streak Restores': 'Serien-Wiederherstellungen', 'Play Streak': 'Spielserie',
        'Year in Review': 'Jahresrückblick', 'Friend Activity': 'Freundesaktivität', 'Notification history': 'Benachrichtigungsverlauf', 'Tools & extras': 'Werkzeuge & Extras', 'Extras settings': 'Extra-Einstellungen', 'Diagnostics': 'Diagnose',
        'Automatic backups': 'Automatische Sicherungen', 'What should I play?': 'Was soll ich spielen?', 'Up Next': 'Als Nächstes', 'Play calendar': 'Spielkalender', 'Library stats': 'Bibliotheksstatistik', 'Co-op finder': 'Koop-Finder',
        'Game journal': 'Spieletagebuch', 'Weekly bingo': 'Wöchentliches Bingo', 'Season': 'Saison', 'Free games & sales': 'Gratisspiele & Angebote', 'Library health': 'Bibliotheks-Check', 'Shutdown timer': 'Abschalt-Timer',
        'Closest to 100%': 'Am nächsten an 100 %', 'Home Title': 'Start', 'Select multiple games': 'Mehrere Spiele auswählen', 'Launch Options': 'Startoptionen', 'Game Notes': 'Spielnotizen', 'Session History': 'Sitzungsverlauf',
        'Screenshots': 'Screenshots', 'Details': 'Details', 'News': 'Neuigkeiten', 'Hide Game': 'Spiel ausblenden', 'Unhide Game': 'Spiel einblenden', 'Add to Favorites': 'Zu Favoriten hinzufügen', 'Remove from Favorites': 'Aus Favoriten entfernen', 'Change Cover': 'Cover ändern',
        'Edit Profile': 'Profil bearbeiten', 'Badges': 'Abzeichen', 'Showcase': 'Vitrine', 'Owned Games': 'Besitzte Spiele', 'Level': 'Level', 'Games': 'Spiele', 'Playtime': 'Spielzeit', 'Loading...': 'Wird geladen...', 'No friends to show.': 'Keine Freunde vorhanden.',
        'Update Now': 'Jetzt aktualisieren', 'Later': 'Später', "What's new": 'Was ist neu', 'Skip this version': 'Diese Version überspringen', 'Back': 'Zurück', 'Next': 'Weiter', 'Done': 'Fertig', 'Yes': 'Ja', 'No': 'Nein', 'OK': 'OK', 'Delete': 'Löschen', 'Add': 'Hinzufügen', 'Remove': 'Entfernen',
        'Appearance (card style, font, UI scale)': 'Aussehen (Kartenstil, Schrift, Skalierung)', 'Keyboard Shortcuts': 'Tastenkürzel', 'Global Hotkeys': 'Globale Tastenkürzel', 'Quit SteamLite': 'SteamLite beenden', 'Go to Home': 'Zum Start', 'Go to Library': 'Zur Bibliothek',
        'Go to Favorites': 'Zu den Favoriten', 'Open Settings': 'Einstellungen öffnen', 'Toggle Friends Panel': 'Freundesliste ein/aus', 'Play Random Game': 'Zufälliges Spiel', 'Free Up Space (disk cleanup)': 'Speicher freigeben (Datenträgerbereinigung)', 'Import Games from Start Menu': 'Spiele aus dem Startmenü importieren',
        'Drops': 'Drops', 'Shop': 'Shop', 'Trophy room': 'Trophäenraum', 'Events': 'Events', 'Claim': 'Abholen', 'Quick access': 'Schnellzugriff', 'Notifications': 'Benachrichtigungen', 'Account': 'Konto', 'Appearance': 'Aussehen', 'Sound & notifications': 'Ton & Benachrichtigungen',
        'Behaviour': 'Verhalten', 'Performance': 'Leistung', 'Updates': 'Updates', 'Backup & data': 'Sicherung & Daten', 'Lucky wheel': 'Glücksrad', 'Spin': 'Drehen'
    };
    L.pt = {
        'Home': 'Início', 'Library': 'Biblioteca', 'Favorites': 'Favoritos', 'Settings': 'Configurações', 'Dashboard': 'Painel', 'Collections': 'Coleções', 'COLLECTIONS': 'COLEÇÕES', 'Profile': 'Perfil', 'Friend Profile': 'Perfil do amigo',
        'Online': 'Online', 'Offline': 'Offline', 'Away': 'Ausente', 'Installed': 'Instalado', 'Not Installed': 'Não instalado', 'Play': 'Jogar', 'Install': 'Instalar', 'Uninstall': 'Desinstalar', 'Cancel': 'Cancelar', 'Save': 'Salvar', 'Close': 'Fechar',
        'Refresh': 'Atualizar', 'Apply': 'Aplicar', 'Locked': 'Bloqueado', 'Search library...': 'Pesquisar na biblioteca...', 'Play Next': 'Jogar a seguir', 'Friends List': 'Lista de amigos', 'Search friends...': 'Pesquisar amigos...', 'Show hidden': 'Mostrar ocultos',
        'Activity': 'Atividade', 'Right-click a friend for more': 'Clique direito em um amigo para mais', 'Application Settings': 'Configurações do aplicativo', 'Modify your preferences below': 'Altere suas preferências abaixo', 'Advanced Settings': 'Configurações avançadas',
        'Save Configuration': 'Salvar configuração', 'Check for Updates': 'Verificar atualizações', 'Filters': 'Filtros', 'Sort By': 'Ordenar por', 'Hide Shared': 'Ocultar compartilhados', 'Show Hidden': 'Mostrar ocultos', 'Compact List': 'Lista compacta',
        'My status': 'Meu status', 'Playing': 'Jogando', 'Backlog': 'Pendente', 'Completed': 'Concluído', 'Dropped': 'Abandonado', 'Inventory': 'Inventário', 'Achievements': 'Conquistas', 'SteamLite Achievements': 'Conquistas do SteamLite', 'Wishlist': 'Lista de desejos',
        'Daily challenges': 'Desafios diários', 'Weekly challenges': 'Desafios semanais', 'Items': 'Itens', 'Level rewards': 'Recompensas de nível', 'Rewards earned': 'Recompensas obtidas', 'Streak Restores': 'Restaurações de sequência', 'Play Streak': 'Sequência de jogo',
        'Year in Review': 'Retrospectiva do ano', 'Friend Activity': 'Atividade dos amigos', 'Notification history': 'Histórico de notificações', 'Tools & extras': 'Ferramentas e extras', 'Extras settings': 'Configurações de extras', 'Diagnostics': 'Diagnóstico',
        'Automatic backups': 'Backups automáticos', 'What should I play?': 'O que jogar?', 'Up Next': 'A seguir', 'Play calendar': 'Calendário de jogo', 'Library stats': 'Estatísticas da biblioteca', 'Co-op finder': 'Buscador de coop',
        'Game journal': 'Diário de jogos', 'Weekly bingo': 'Bingo semanal', 'Season': 'Temporada', 'Free games & sales': 'Jogos grátis e promoções', 'Library health': 'Saúde da biblioteca', 'Shutdown timer': 'Temporizador de desligamento',
        'Closest to 100%': 'Mais perto de 100%', 'Home Title': 'Início', 'Select multiple games': 'Selecionar vários jogos', 'Launch Options': 'Opções de inicialização', 'Game Notes': 'Notas do jogo', 'Session History': 'Histórico de sessões',
        'Screenshots': 'Capturas de tela', 'Details': 'Detalhes', 'News': 'Notícias', 'Hide Game': 'Ocultar jogo', 'Unhide Game': 'Mostrar jogo', 'Add to Favorites': 'Adicionar aos favoritos', 'Remove from Favorites': 'Remover dos favoritos', 'Change Cover': 'Trocar capa',
        'Edit Profile': 'Editar perfil', 'Badges': 'Emblemas', 'Showcase': 'Vitrine', 'Owned Games': 'Jogos possuídos', 'Level': 'Nível', 'Games': 'Jogos', 'Playtime': 'Tempo de jogo', 'Loading...': 'Carregando...', 'No friends to show.': 'Nenhum amigo para mostrar.',
        'Update Now': 'Atualizar agora', 'Later': 'Mais tarde', "What's new": 'Novidades', 'Skip this version': 'Ignorar esta versão', 'Back': 'Voltar', 'Next': 'Avançar', 'Done': 'Concluído', 'Yes': 'Sim', 'No': 'Não', 'OK': 'OK', 'Delete': 'Excluir', 'Add': 'Adicionar', 'Remove': 'Remover',
        'Appearance (card style, font, UI scale)': 'Aparência (estilo dos cartões, fonte, escala)', 'Keyboard Shortcuts': 'Atalhos do teclado', 'Global Hotkeys': 'Atalhos globais', 'Quit SteamLite': 'Sair do SteamLite', 'Go to Home': 'Ir para o início', 'Go to Library': 'Ir para a biblioteca',
        'Go to Favorites': 'Ir para os favoritos', 'Open Settings': 'Abrir configurações', 'Toggle Friends Panel': 'Mostrar/ocultar amigos', 'Play Random Game': 'Jogar aleatório', 'Free Up Space (disk cleanup)': 'Liberar espaço (limpeza de disco)', 'Import Games from Start Menu': 'Importar jogos do menu Iniciar',
        'Drops': 'Presentes', 'Shop': 'Loja', 'Trophy room': 'Sala de troféus', 'Events': 'Eventos', 'Claim': 'Resgatar', 'Quick access': 'Acesso rápido', 'Notifications': 'Notificações', 'Account': 'Conta', 'Appearance': 'Aparência', 'Sound & notifications': 'Som e notificações',
        'Behaviour': 'Comportamento', 'Performance': 'Desempenho', 'Updates': 'Atualizações', 'Backup & data': 'Backup e dados', 'Lucky wheel': 'Roleta da sorte', 'Spin': 'Girar'
    };
    L.it = {
        'Home': 'Home', 'Library': 'Libreria', 'Favorites': 'Preferiti', 'Settings': 'Impostazioni', 'Dashboard': 'Dashboard', 'Collections': 'Raccolte', 'COLLECTIONS': 'RACCOLTE', 'Profile': 'Profilo', 'Friend Profile': "Profilo dell'amico",
        'Online': 'Online', 'Offline': 'Offline', 'Away': 'Assente', 'Installed': 'Installato', 'Not Installed': 'Non installato', 'Play': 'Gioca', 'Install': 'Installa', 'Uninstall': 'Disinstalla', 'Cancel': 'Annulla', 'Save': 'Salva', 'Close': 'Chiudi',
        'Refresh': 'Aggiorna', 'Apply': 'Applica', 'Locked': 'Bloccato', 'Search library...': 'Cerca nella libreria...', 'Play Next': 'Gioca dopo', 'Friends List': 'Elenco amici', 'Search friends...': 'Cerca amici...', 'Show hidden': 'Mostra nascosti',
        'Activity': 'Attività', 'Right-click a friend for more': "Clic destro su un amico per altro", 'Application Settings': "Impostazioni dell'app", 'Modify your preferences below': 'Modifica le tue preferenze qui sotto', 'Advanced Settings': 'Impostazioni avanzate',
        'Save Configuration': 'Salva configurazione', 'Check for Updates': 'Cerca aggiornamenti', 'Filters': 'Filtri', 'Sort By': 'Ordina per', 'Hide Shared': 'Nascondi condivisi', 'Show Hidden': 'Mostra nascosti', 'Compact List': 'Elenco compatto',
        'My status': 'Il mio stato', 'Playing': 'In corso', 'Backlog': 'Da giocare', 'Completed': 'Completato', 'Dropped': 'Abbandonato', 'Inventory': 'Inventario', 'Achievements': 'Obiettivi', 'SteamLite Achievements': 'Obiettivi SteamLite', 'Wishlist': 'Lista desideri',
        'Daily challenges': 'Sfide giornaliere', 'Weekly challenges': 'Sfide settimanali', 'Items': 'Oggetti', 'Level rewards': 'Ricompense di livello', 'Rewards earned': 'Ricompense ottenute', 'Streak Restores': 'Ripristini serie', 'Play Streak': 'Serie di gioco',
        'Year in Review': "Riepilogo dell'anno", 'Friend Activity': 'Attività degli amici', 'Notification history': 'Cronologia notifiche', 'Tools & extras': 'Strumenti ed extra', 'Extras settings': 'Impostazioni extra', 'Diagnostics': 'Diagnostica',
        'Automatic backups': 'Backup automatici', 'What should I play?': 'A cosa gioco?', 'Up Next': 'Prossimi', 'Play calendar': 'Calendario di gioco', 'Library stats': 'Statistiche della libreria', 'Co-op finder': 'Trova coop',
        'Game journal': 'Diario di gioco', 'Weekly bingo': 'Bingo settimanale', 'Season': 'Stagione', 'Free games & sales': 'Giochi gratis e saldi', 'Library health': 'Stato della libreria', 'Shutdown timer': 'Timer di spegnimento',
        'Closest to 100%': 'Più vicini al 100%', 'Home Title': 'Home', 'Select multiple games': 'Seleziona più giochi', 'Launch Options': 'Opzioni di avvio', 'Game Notes': 'Note del gioco', 'Session History': 'Cronologia sessioni',
        'Screenshots': 'Schermate', 'Details': 'Dettagli', 'News': 'Notizie', 'Hide Game': 'Nascondi gioco', 'Unhide Game': 'Mostra gioco', 'Add to Favorites': 'Aggiungi ai preferiti', 'Remove from Favorites': 'Rimuovi dai preferiti', 'Change Cover': 'Cambia copertina',
        'Edit Profile': 'Modifica profilo', 'Badges': 'Distintivi', 'Showcase': 'Vetrina', 'Owned Games': 'Giochi posseduti', 'Level': 'Livello', 'Games': 'Giochi', 'Playtime': 'Tempo di gioco', 'Loading...': 'Caricamento...', 'No friends to show.': 'Nessun amico da mostrare.',
        'Update Now': 'Aggiorna ora', 'Later': 'Più tardi', "What's new": 'Novità', 'Skip this version': 'Salta questa versione', 'Back': 'Indietro', 'Next': 'Avanti', 'Done': 'Fatto', 'Yes': 'Sì', 'No': 'No', 'OK': 'OK', 'Delete': 'Elimina', 'Add': 'Aggiungi', 'Remove': 'Rimuovi',
        'Appearance (card style, font, UI scale)': 'Aspetto (stile delle schede, carattere, scala)', 'Keyboard Shortcuts': 'Scorciatoie da tastiera', 'Global Hotkeys': 'Scorciatoie globali', 'Quit SteamLite': 'Esci da SteamLite', 'Go to Home': 'Vai alla home', 'Go to Library': 'Vai alla libreria',
        'Go to Favorites': 'Vai ai preferiti', 'Open Settings': 'Apri impostazioni', 'Toggle Friends Panel': 'Mostra/nascondi amici', 'Play Random Game': 'Gioca a caso', 'Free Up Space (disk cleanup)': 'Libera spazio (pulizia disco)', 'Import Games from Start Menu': 'Importa giochi dal menu Start',
        'Drops': 'Regali', 'Shop': 'Negozio', 'Trophy room': 'Sala dei trofei', 'Events': 'Eventi', 'Claim': 'Riscatta', 'Quick access': 'Accesso rapido', 'Notifications': 'Notifiche', 'Account': 'Account', 'Appearance': 'Aspetto', 'Sound & notifications': 'Suoni e notifiche',
        'Behaviour': 'Comportamento', 'Performance': 'Prestazioni', 'Updates': 'Aggiornamenti', 'Backup & data': 'Backup e dati', 'Lucky wheel': 'Ruota della fortuna', 'Spin': 'Gira'
    };
    // English names are shown in the language's own words
    const NAMES = { es: 'Español', fr: 'Français', de: 'Deutsch', pt: 'Português', it: 'Italiano' };
    Object.keys(L).forEach(k => { SLF.DICTS[k] = L[k]; SLF.langNames[k] = NAMES[k]; });
    // the Bulgarian pack also gets the new screen names
    Object.assign(SLF.DICTS.bg, { 'Drops': 'Подаръци', 'Shop': 'Магазин', 'Trophy room': 'Зала с трофеи', 'Events': 'Събития', 'Claim': 'Вземи', 'Quick access': 'Бърз достъп', 'Notifications': 'Известия', 'Lucky wheel': 'Колело на късмета', 'Spin': 'Завърти' });
})();
