ALTER TABLE msgs ADD COLUMN kind TEXT NOT NULL DEFAULT 'text';
ALTER TABLE msgs ADD COLUMN data TEXT NOT NULL DEFAULT '';
ALTER TABLE msgs ADD COLUMN reply_to INTEGER NOT NULL DEFAULT 0;
ALTER TABLE msgs ADD COLUMN edited INTEGER NOT NULL DEFAULT 0;
ALTER TABLE msgs ADD COLUMN pinned INTEGER NOT NULL DEFAULT 0;
ALTER TABLE members ADD COLUMN muted INTEGER NOT NULL DEFAULT 0;
ALTER TABLE accounts ADD COLUMN bio TEXT NOT NULL DEFAULT '';
