ALTER TABLE daystreak ADD COLUMN restores INTEGER NOT NULL DEFAULT 0;
ALTER TABLE daystreak ADD COLUMN rec_until TEXT NOT NULL DEFAULT '';
ALTER TABLE daystreak ADD COLUMN rec_prev INTEGER NOT NULL DEFAULT 0;
