CREATE TABLE IF NOT EXISTS track (uid TEXT NOT NULL, appid INTEGER NOT NULL, name TEXT NOT NULL, pct INTEGER NOT NULL DEFAULT 20, notified INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (uid, appid));
CREATE TABLE IF NOT EXISTS sfold (id TEXT PRIMARY KEY, owner TEXT NOT NULL, name TEXT NOT NULL, items TEXT NOT NULL DEFAULT '[]', at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS sfold_m (id TEXT NOT NULL, uid TEXT NOT NULL, PRIMARY KEY (id, uid));
CREATE INDEX IF NOT EXISTS sfold_m_uid ON sfold_m(uid);
ALTER TABLE pcs ADD COLUMN game_id INTEGER NOT NULL DEFAULT 0;
ALTER TABLE pcs ADD COLUMN game_name TEXT NOT NULL DEFAULT '';
ALTER TABLE pcs ADD COLUMN since INTEGER NOT NULL DEFAULT 0;
ALTER TABLE userdata ADD COLUMN phone TEXT NOT NULL DEFAULT '{}';
ALTER TABLE userdata ADD COLUMN phone_at INTEGER NOT NULL DEFAULT 0;
