CREATE TABLE IF NOT EXISTS sched (id INTEGER PRIMARY KEY AUTOINCREMENT, uid TEXT NOT NULL, conv TEXT NOT NULL, text TEXT NOT NULL, send_at INTEGER NOT NULL, created INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS sched_at ON sched(send_at);
CREATE TABLE IF NOT EXISTS wishshare (uid TEXT PRIMARY KEY, code TEXT NOT NULL UNIQUE, name TEXT NOT NULL, items TEXT NOT NULL, at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS freegames (appid INTEGER PRIMARY KEY, name TEXT NOT NULL, at INTEGER NOT NULL);
ALTER TABLE profiles ADD COLUMN status TEXT NOT NULL DEFAULT '';
ALTER TABLE profiles ADD COLUMN status_until INTEGER NOT NULL DEFAULT 0;
