CREATE TABLE IF NOT EXISTS profiles (uid TEXT PRIMARY KEY, tagline TEXT NOT NULL DEFAULT '', accent TEXT NOT NULL DEFAULT '', frame TEXT NOT NULL DEFAULT '', title TEXT NOT NULL DEFAULT '', banner TEXT NOT NULL DEFAULT '', showcase TEXT NOT NULL DEFAULT '[]', hide_badges INTEGER NOT NULL DEFAULT 0, prestige INTEGER NOT NULL DEFAULT 0, hide_read INTEGER NOT NULL DEFAULT 0, hide_typing INTEGER NOT NULL DEFAULT 0, at INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS activity (id INTEGER PRIMARY KEY AUTOINCREMENT, uid TEXT NOT NULL, kind TEXT NOT NULL, text TEXT NOT NULL, appid INTEGER NOT NULL DEFAULT 0, at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS activity_at ON activity(at);
CREATE INDEX IF NOT EXISTS activity_uid ON activity(uid, at);
CREATE TABLE IF NOT EXISTS gvotes (msg INTEGER NOT NULL, uid TEXT NOT NULL, opt INTEGER NOT NULL, PRIMARY KEY (msg, uid));
ALTER TABLE members ADD COLUMN muted_until INTEGER NOT NULL DEFAULT 0;
