CREATE TABLE IF NOT EXISTS wish (uid TEXT NOT NULL, appid INTEGER NOT NULL, name TEXT NOT NULL, notified INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (uid, appid));
CREATE INDEX IF NOT EXISTS wish_app ON wish(appid);
CREATE TABLE IF NOT EXISTS deals (appid INTEGER PRIMARY KEY, pct INTEGER NOT NULL, price TEXT NOT NULL, at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS pcs (uid TEXT PRIMARY KEY, at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS cmds (id TEXT PRIMARY KEY, uid TEXT NOT NULL, appid INTEGER NOT NULL, name TEXT NOT NULL, at INTEGER NOT NULL, taken INTEGER NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS cmds_uid ON cmds(uid, taken);
