-- SteamLite Online database (Cloudflare D1 / SQLite)
CREATE TABLE IF NOT EXISTS kv (k TEXT PRIMARY KEY, v TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS rate (k TEXT PRIMARY KEY, n INTEGER NOT NULL, exp INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS votes (poll_id TEXT NOT NULL, uid TEXT NOT NULL, option_id TEXT NOT NULL, PRIMARY KEY (poll_id, uid));
CREATE TABLE IF NOT EXISTS lb (uid TEXT PRIMARY KEY, name TEXT NOT NULL, level INTEGER NOT NULL, hours INTEGER NOT NULL, streak INTEGER NOT NULL, achievements INTEGER NOT NULL, games INTEGER NOT NULL, at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS lb_level ON lb(level DESC, hours DESC);
CREATE TABLE IF NOT EXISTS themes (id TEXT PRIMARY KEY, uid TEXT NOT NULL, status TEXT NOT NULL, at INTEGER NOT NULL, name TEXT NOT NULL, blurb TEXT NOT NULL, author TEXT NOT NULL, vars TEXT NOT NULL, css TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS themes_status ON themes(status, at);
CREATE TABLE IF NOT EXISTS theme_likes (theme_id TEXT NOT NULL, uid TEXT NOT NULL, PRIMARY KEY (theme_id, uid));
