-- SteamLite Online database (Cloudflare D1 / SQLite)
CREATE TABLE IF NOT EXISTS kv (k TEXT PRIMARY KEY, v TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS rate (k TEXT PRIMARY KEY, n INTEGER NOT NULL, exp INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS votes (poll_id TEXT NOT NULL, uid TEXT NOT NULL, option_id TEXT NOT NULL, PRIMARY KEY (poll_id, uid));
CREATE TABLE IF NOT EXISTS lb (uid TEXT PRIMARY KEY, name TEXT NOT NULL, level INTEGER NOT NULL, hours INTEGER NOT NULL, streak INTEGER NOT NULL, achievements INTEGER NOT NULL, games INTEGER NOT NULL, at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS lb_level ON lb(level DESC, hours DESC);
CREATE TABLE IF NOT EXISTS themes (id TEXT PRIMARY KEY, uid TEXT NOT NULL, status TEXT NOT NULL, at INTEGER NOT NULL, name TEXT NOT NULL, blurb TEXT NOT NULL, author TEXT NOT NULL, vars TEXT NOT NULL, css TEXT NOT NULL, downloads INTEGER NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS themes_status ON themes(status, at);
CREATE TABLE IF NOT EXISTS theme_likes (theme_id TEXT NOT NULL, uid TEXT NOT NULL, PRIMARY KEY (theme_id, uid));

-- accounts ("Sign in with Steam")
CREATE TABLE IF NOT EXISTS accounts (steamid TEXT PRIMARY KEY, uid TEXT NOT NULL UNIQUE, name TEXT NOT NULL, avatar TEXT NOT NULL DEFAULT '', verified INTEGER NOT NULL DEFAULT 0, bio TEXT NOT NULL DEFAULT '', created INTEGER NOT NULL, last INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS sessions (h TEXT PRIMARY KEY, steamid TEXT NOT NULL, created INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS sessions_steamid ON sessions(steamid);
CREATE TABLE IF NOT EXISTS auth_pending (n TEXT PRIMARY KEY, token TEXT NOT NULL, steamid TEXT NOT NULL, name TEXT NOT NULL, exp INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS backups (steamid TEXT PRIMARY KEY, data TEXT NOT NULL, prev TEXT, at INTEGER NOT NULL, prev_at INTEGER NOT NULL DEFAULT 0);

-- messages, groups and friend streaks
CREATE TABLE IF NOT EXISTS friends (a TEXT NOT NULL, b TEXT NOT NULL, status TEXT NOT NULL, req_by TEXT NOT NULL, at INTEGER NOT NULL, PRIMARY KEY (a, b));
CREATE INDEX IF NOT EXISTS friends_b ON friends(b);
CREATE TABLE IF NOT EXISTS blocks (uid TEXT NOT NULL, target TEXT NOT NULL, PRIMARY KEY (uid, target));
CREATE TABLE IF NOT EXISTS convs (id TEXT PRIMARY KEY, kind TEXT NOT NULL, name TEXT NOT NULL, owner TEXT NOT NULL, created INTEGER NOT NULL, last_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS members (conv TEXT NOT NULL, uid TEXT NOT NULL, role TEXT NOT NULL, joined INTEGER NOT NULL, last_read INTEGER NOT NULL DEFAULT 0, muted INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (conv, uid));
CREATE INDEX IF NOT EXISTS members_uid ON members(uid);
CREATE TABLE IF NOT EXISTS msgs (id INTEGER PRIMARY KEY AUTOINCREMENT, conv TEXT NOT NULL, uid TEXT NOT NULL, text TEXT NOT NULL, at INTEGER NOT NULL, kind TEXT NOT NULL DEFAULT 'text', data TEXT NOT NULL DEFAULT '', reply_to INTEGER NOT NULL DEFAULT 0, edited INTEGER NOT NULL DEFAULT 0, pinned INTEGER NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS msgs_conv ON msgs(conv, id);
CREATE TABLE IF NOT EXISTS streaks (a TEXT NOT NULL, b TEXT NOT NULL, streak INTEGER NOT NULL DEFAULT 0, best INTEGER NOT NULL DEFAULT 0, last_day INTEGER NOT NULL DEFAULT 0, a_day INTEGER NOT NULL DEFAULT 0, b_day INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (a, b));
CREATE TABLE IF NOT EXISTS reports (id TEXT PRIMARY KEY, reporter TEXT NOT NULL, target TEXT NOT NULL, conv TEXT NOT NULL, snap TEXT NOT NULL, reason TEXT NOT NULL, at INTEGER NOT NULL, status TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS bans (uid TEXT PRIMARY KEY, until INTEGER NOT NULL, reason TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS typing (conv TEXT NOT NULL, uid TEXT NOT NULL, until INTEGER NOT NULL, PRIMARY KEY (conv, uid));
CREATE TABLE IF NOT EXISTS apikeys (steamid TEXT PRIMARY KEY, enc TEXT NOT NULL, iv TEXT NOT NULL, at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS reactions (msg_id INTEGER NOT NULL, uid TEXT NOT NULL, emoji TEXT NOT NULL, PRIMARY KEY (msg_id, uid, emoji));
CREATE TABLE IF NOT EXISTS presence (uid TEXT PRIMARY KEY, game_id INTEGER NOT NULL DEFAULT 0, game_name TEXT NOT NULL DEFAULT '', at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS stats (uid TEXT PRIMARY KEY, level INTEGER NOT NULL, hours INTEGER NOT NULL, streak INTEGER NOT NULL, achievements INTEGER NOT NULL, games INTEGER NOT NULL, at INTEGER NOT NULL, flags INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS lists (id TEXT PRIMARY KEY, uid TEXT NOT NULL, title TEXT NOT NULL, items TEXT NOT NULL, at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS lists_uid ON lists(uid);
CREATE TABLE IF NOT EXISTS challenges (id TEXT PRIMARY KEY, owner TEXT NOT NULL, name TEXT NOT NULL, metric TEXT NOT NULL, startsat INTEGER NOT NULL, endsat INTEGER NOT NULL, conv TEXT NOT NULL, announced INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS challenge_members (cid TEXT NOT NULL, uid TEXT NOT NULL, baseline INTEGER, PRIMARY KEY (cid, uid));
CREATE INDEX IF NOT EXISTS challenge_members_uid ON challenge_members(uid);
CREATE TABLE IF NOT EXISTS audit (at INTEGER NOT NULL, action TEXT NOT NULL, target TEXT NOT NULL, detail TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS media (id TEXT PRIMARY KEY, uid TEXT NOT NULL, mime TEXT NOT NULL, data TEXT NOT NULL, at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS media_at ON media(at);

CREATE TABLE IF NOT EXISTS devices (token TEXT PRIMARY KEY, uid TEXT NOT NULL, at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS devices_uid ON devices(uid);

CREATE TABLE IF NOT EXISTS wish (uid TEXT NOT NULL, appid INTEGER NOT NULL, name TEXT NOT NULL, notified INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (uid, appid));
CREATE INDEX IF NOT EXISTS wish_app ON wish(appid);
CREATE TABLE IF NOT EXISTS deals (appid INTEGER PRIMARY KEY, pct INTEGER NOT NULL, price TEXT NOT NULL, at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS pcs (uid TEXT PRIMARY KEY, at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS cmds (id TEXT PRIMARY KEY, uid TEXT NOT NULL, appid INTEGER NOT NULL, name TEXT NOT NULL, at INTEGER NOT NULL, taken INTEGER NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS cmds_uid ON cmds(uid, taken);

CREATE TABLE IF NOT EXISTS profiles (uid TEXT PRIMARY KEY, tagline TEXT NOT NULL DEFAULT '', accent TEXT NOT NULL DEFAULT '', frame TEXT NOT NULL DEFAULT '', title TEXT NOT NULL DEFAULT '', banner TEXT NOT NULL DEFAULT '', showcase TEXT NOT NULL DEFAULT '[]', hide_badges INTEGER NOT NULL DEFAULT 0, prestige INTEGER NOT NULL DEFAULT 0, hide_read INTEGER NOT NULL DEFAULT 0, hide_typing INTEGER NOT NULL DEFAULT 0, at INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS activity (id INTEGER PRIMARY KEY AUTOINCREMENT, uid TEXT NOT NULL, kind TEXT NOT NULL, text TEXT NOT NULL, appid INTEGER NOT NULL DEFAULT 0, at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS activity_at ON activity(at);
CREATE INDEX IF NOT EXISTS activity_uid ON activity(uid, at);
CREATE TABLE IF NOT EXISTS gvotes (msg INTEGER NOT NULL, uid TEXT NOT NULL, opt INTEGER NOT NULL, PRIMARY KEY (msg, uid));
-- for databases made before 1.2.0 (run once): ALTER TABLE members ADD COLUMN muted_until INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS daystreak (uid TEXT PRIMARY KEY, cur INTEGER NOT NULL DEFAULT 0, best INTEGER NOT NULL DEFAULT 0, last_day TEXT NOT NULL DEFAULT '', phone_days TEXT NOT NULL DEFAULT '[]', at INTEGER NOT NULL DEFAULT 0);

-- group pictures (run once on an existing database): ALTER TABLE convs ADD COLUMN avatar TEXT NOT NULL DEFAULT '';

-- 1.2.1 (run once on an existing database)
CREATE TABLE IF NOT EXISTS sched (id INTEGER PRIMARY KEY AUTOINCREMENT, uid TEXT NOT NULL, conv TEXT NOT NULL, text TEXT NOT NULL, send_at INTEGER NOT NULL, created INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS sched_at ON sched(send_at);
CREATE TABLE IF NOT EXISTS wishshare (uid TEXT PRIMARY KEY, code TEXT NOT NULL UNIQUE, name TEXT NOT NULL, items TEXT NOT NULL, at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS freegames (appid INTEGER PRIMARY KEY, name TEXT NOT NULL, at INTEGER NOT NULL);
ALTER TABLE profiles ADD COLUMN status TEXT NOT NULL DEFAULT '';
ALTER TABLE profiles ADD COLUMN status_until INTEGER NOT NULL DEFAULT 0;

-- 1.2.1 streak sync (run once on an existing database)
ALTER TABLE daystreak ADD COLUMN restores INTEGER NOT NULL DEFAULT 0;
ALTER TABLE daystreak ADD COLUMN rec_until TEXT NOT NULL DEFAULT '';
ALTER TABLE daystreak ADD COLUMN rec_prev INTEGER NOT NULL DEFAULT 0;
